[server]
headless = true
address = "0.0.0.0"
port = 15000

[theme]
primaryColor = "#EE0C5D"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1a1a1a"
font = "sans serif"

[browser]
gatherUsageStats = false
